### ISSUE TITLE
`HH.a [ HP.name "foo" ] []` doesn't work

### ISSUE THREAD

**Issue by Boscop** [slamdata/purescript-dom-indexed#12]
`HH.a [ HP.name "foo" ] []` doesn't work because [HTMLa](https://pursuit.purescript.org/packages/purescript-dom-indexed/5.0.0/docs/DOM.HTML.Indexed#t:HTMLa) doesn't have `name :: String`.

**Comment by garyb** [comment]
Indeed it does not: https://www.w3.org/TR/html5/textlevel-semantics.html#the-a-element :smile:

Set the `id` instead: https://www.w3.org/TR/html5/browsers.html#navigating-to-a-fragment-identifier
